name: Deploy to latest on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: now --confirm --prod --local-config now-latest.json --token YcfsC2zICpTwI6jEwWyD179t
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
